# Use Node.js base image
FROM node:23.3.0-alpine

WORKDIR /app

# Copy package.json and install dependencies
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Copy server files
COPY server ./server
COPY tsconfig.server.json ./

# Build the server
RUN yarn build:server

# Set working directory to the built output
WORKDIR /app/server/dist

# Expose port 5000 (or whatever your backend uses)
EXPOSE 5002

# Start the server
CMD ["node", "index.js"]